CREATE DATABASE DEMO;

CREATE SCHEMA DEMO.DEMO_SCHEMA;


CREATE STORAGE INTEGRATION s3_int
		  TYPE = EXTERNAL_STAGE
		  STORAGE_PROVIDER = 'S3'
		  STORAGE_AWS_ROLE_ARN = 'arn:aws:iam::671516769773:role/aws-to-snow0'
		  ENABLED = TRUE
		  STORAGE_ALLOWED_LOCATIONS = ('s3://snow-to-aws0');


DESC INTEGRATION s3_int;

CREATE STAGE DEMO.DEMO_SCHEMA.my_s3_stage
STORAGE_INTEGRATION = s3_int
URL = 's3://snow-to-aws0';

LIST @DEMO.DEMO_SCHEMA.my_s3_stage;
